name: release version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Build
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"
          maven-args: "clean install"
      - name: Prepare
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"
          maven-args: "release:prepare"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"
          maven-args: "release:perform"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}